### PR TITLE
Moving the CI scripts

### PR DESCRIPTION
**Pull request by henryiii**
This would move `ci-scripts` to `.ci` if accepted.

### CODE REVIEW

**Comment by HDembinski** [comment]
I am so-so on this. i don't see why the ci scripts should be hidden.

**Comment by HDembinski** [comment]
Reading your argument in the other PR, I am with renaming to `.ci`.

**Comment by henryiii** [comment]
I may have to make the azure support folder configurable somehow anyway, so only make the change if you do like it.

**Comment by HDembinski** [comment]
@henryiii I am not strongly attached to the current folder name and I value consistency. I am ok with this PR if it helps to make scikit-hep projects more consistent.

**Pull request merged**
