### PR TITLE
added msvc fixes from pybind11/cmake_example by henryiii

### PR DESCRIPTION
**Pull request by HDembinski**

### CODE REVIEW

**Comment by HDembinski** [comment]
Closes #570

**Comment by henryiii** [comment]
You need to remove the `def run(self):...` method. It's not initializing the compiler (which is why self.compiler is empty). The default run method is correct - I fixed this bug in the old example when I rewrote it: https://github.com/pybind/cmake_example/blob/580c5fd29d4651db99d8874714b07c0c49a53f8a/setup.py#L39

**Comment by henryiii** [comment]
I can apply this as a patch to see if it fixes conda without having to make a release, so we don’t get stuck in a loop if there is still a problem. Will apply soon.

**Comment by henryiii** [comment]
Thanks for keeping the CI changes separate, I would have had to manually modify the patch (I found out because I accidentally applied the patch from my branch instead of this one).

**Comment by henryiii** [comment]
I can verify that this patch fixed conda-forge! A patched 2.0.0 is released. Thanks for including `CMAKE_BUILD_PARALLEL_LEVEL` too, as that let me fix the out-of-memory error on Travis as well.

**Comment by henryiii** [comment]
We (you, me, or @chrisburr, probably) need to remember to simplify the recipe when 2.0.1 or 2.1.0 comes out, dropping this patch and the manual inclusion of the tests via git.

**Comment by HDembinski** [comment]
Thank you very much for helping with this and having the eye on conda-forge @henryiii

**Pull request merged**
