### PR TITLE
fix: Allow subclasses to use from_array_func

### PR DESCRIPTION
**Pull request by henryiii**
Reported by @kratsg

### CODE REVIEW

**Comment by henryiii** [comment]
I don't seem to be able to get rid of the stale "release check" check, but since this is going to develop now, it shouldn't matter.

**Comment by HDembinski** [comment]
The failures are unrelated to the patch, so I am merging, thanks!

**Comment by HDembinski** [comment]
Very strange that this triggered the CI jobs for PRs on master.

**Comment by henryiii** [comment]
It pulled in history from the last PR, since it was the same commit. Why that one targeted master instead of develop, I don't know...

**Pull request merged**
