### PR TITLE
Add CI test with Gammapy

### PR DESCRIPTION
**Pull request by cdeil**
This PR adds a CI test for Gammapy.

See https://github.com/scikit-hep/iminuit/issues/337#issuecomment-493412424

### CODE REVIEW

**Comment by cdeil** [comment]
I don't think it matters much if we test the latest stable or the Gammapy dev version. In Gammapy we have bi-monthly releases, and the goal should be for iminuit to be backwards-compat, i.e. work with all the recent releases of Gammapy from the past months.

So clearly testing more / other Gammapy versions is possible, but overall it shouldn't matter much.

@HDembinski - What are the other "big" customers - should we add any other projects that use iminuit in a similar way?

**Comment by cdeil** [comment]
The test now runs and shows the issue in #337 , see
https://travis-ci.org/scikit-hep/iminuit/jobs/533805080#L944

The build still passes. I'll try putting `;` now as suggested here:
https://github.com/nipy/dipy/blob/8379bbde5bfe07ed2d6fa48f4f08953b298f62f5/.travis.yml#L6

**Comment by cdeil** [comment]
The problem was that the exit status was always zero.

Now I changed to this, which should return non-zero exit status if there's a test fail:
```
- python -c "import sys, gammapy; sys.exit(gammapy.test())"
```

@HDembinski - Assigning this PR to you.
You could merge it now and have the fail in master, or first fix the regression, as you prefer.

**Comment by cdeil** [comment]
It's working: https://travis-ci.org/scikit-hep/iminuit/jobs/533816072#L1193
```
The command "python -c "import sys, gammapy; sys.exit(gammapy.test())"" exited with 1.
```

**Comment by henryiii** [comment]
This is great +1

**Comment by HDembinski** [comment]
@cdeil Thank you! The other "consumer" is probfit, I will add an integration test later. I checked probfit before the broken release and it didn't reveal the error.

**Comment by HDembinski** [comment]
@cdeil I believe that "integration tests" are an intermediate solution and not a good idea in general. They reveal deficiencies in the iminuit internal tests. Every library should test its public interface thoroughly. If that's the case, then there is no way to introduce a breaking change without breaking a test. A library shouldn't rely on its consumers for that.

**Comment by henryiii** [comment]
@HDembinski I agree. Could I request that when you add an integration test for probfit, you use git rather than pypi when you pip install it? I'd like to avoid having our own CI artificially adding to our PyPI download stats (though at some point this should be fixed, pip 19.1 is supposed to report when it runs in CI).

**Comment by henryiii** [comment]
PS: Not a big deal if you prefer the PyPI package, there already are other packages in Scikit-HEP that do not do this correctly either; and it's harder to do if you have a dependency of a dependency.

**Comment by HDembinski** [comment]
I decided against adding integration tests to the CI. I will add some integration test scripts in the CI script folder that can be run manually before making a release, but I think it is a waste of resources to run gammapy and probfit tests regularly in CI.

**Comment by HDembinski** [comment]
And when failures are discovered by doing an integration tests that iminuits own tests didn't reveal, then iminuit's tests must be extended. I did that for the API that broke gammapy.

**Comment by HDembinski** [comment]
> Could I request that when you add an integration test for probfit, you use git rather than pypi when you pip install it?

Ok, but for an integration test, it is nice to install from PyPI, because you automatically get the latest release. When installing from github, you have to set the release tag manually and update it.

**Comment by henryiii** [comment]
PyPI is not bad for one that doesn't run very often - and hopefully the change in pip 19.1 will help in the future. I would set it up to only run on master - you don't need to run integration tests on develop. It really should run on Travis or Azure, though, and not only on a personal computer somewhere. It's trivial to set up a new Azure pipeline for this; you can even set a date based trigger, but just adding a "skip if not on master" to travis for this line would be fine. You can add a note in CONTRIBUTING.md or somewhere that any failing integration tests need a new unit test as well to fix.

**Comment by HDembinski** [comment]
I am only run them manually on a release now, so they won't be running very often.

**Comment by HDembinski** [comment]
I don't think CONTRIBUTING.md is the right place, since this is information for the maintainer, not for the contributor. I will put the information somewhere, though.

**Pull request merged**
